import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { useEffect } from "react";

const PrivacyPolicy = () => {
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, []);

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <main className="container mx-auto max-w-4xl px-4 py-24">
        <article className="prose prose-lg dark:prose-invert max-w-none">
          <h1 className="text-4xl font-bold mb-4">Privacy Policy</h1>
          <p className="text-muted-foreground mb-8">Last updated: November 4, 2025</p>
          
          <p>This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.</p>
          
          <p>We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy. This Privacy Policy has been created with the help of the <a href="https://www.termsfeed.com/privacy-policy-generator/" target="_blank" rel="noopener noreferrer" className="text-primary hover:underline">Privacy Policy Generator</a>.</p>
          
          <h2 className="text-3xl font-bold mt-12 mb-4">Interpretation and Definitions</h2>
          
          <h3 className="text-2xl font-semibold mt-8 mb-3">Interpretation</h3>
          <p>The words whose initial letters are capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.</p>
          
          <h3 className="text-2xl font-semibold mt-8 mb-3">Definitions</h3>
          <p>For the purposes of this Privacy Policy:</p>
          
          <ul className="list-disc pl-6 space-y-3">
            <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
            <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
            <li><strong>Application</strong> refers to Smart Asstor, the software program provided by the Company.</li>
            <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Smart Asstor.</li>
            <li><strong>Country</strong> refers to: Nova Scotia, Canada</li>
            <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
            <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
            <li><strong>Service</strong> refers to the Application.</li>
            <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
            <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
            <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
          </ul>
          
          <h2 className="text-3xl font-bold mt-12 mb-4">Collecting and Using Your Personal Data</h2>
          
          <h3 className="text-2xl font-semibold mt-8 mb-3">1. Introduction</h3>
          <p>This Privacy Policy describes how we collect, use, and handle your personal information when you use our Service.</p>

          <h3 className="text-2xl font-semibold mt-8 mb-3">2. Information We Collect</h3>
          <p>We collect the following information that you provide to us:</p>
          
          <ul className="list-disc pl-6 space-y-2">
            <li>Your email address</li>
            <li>Data that you input into our Service</li>
          </ul>

          <h3 className="text-2xl font-semibold mt-8 mb-3">3. How We Use Your Information</h3>
          <p>We use the information we collect for the following purposes:</p>

          <h4 className="text-xl font-semibold mt-6 mb-2">3.1 Service Provision and Maintenance</h4>
          <p>To provide and maintain our Service, including adding your email and data you input to a database for your private use.</p>

          <h3 className="text-2xl font-semibold mt-8 mb-3">4. Data Storage</h3>
          <p>The information you provide, including your email address and input data, is stored in a database dedicated to your private use.</p>

          <h3 className="text-2xl font-semibold mt-8 mb-3">5. Data Security</h3>
          <p>We implement appropriate technical and organizational measures to protect your personal information against unauthorized access, alteration, disclosure, or destruction.</p>
          
          <h3 className="text-2xl font-semibold mt-8 mb-3">Retention of Your Personal Data</h3>
          <p>The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations (for example, if we are required to retain your data to comply with applicable laws), resolve disputes, and enforce our legal agreements and policies.</p>
          
          <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for a shorter period of time, except when this data is used to strengthen the security or to improve the functionality of Our Service, or We are legally obligated to retain this data for longer periods.</p>
          
          <h3 className="text-2xl font-semibold mt-8 mb-3">Transfer of Your Personal Data</h3>
          <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ from those from Your jurisdiction.</p>
          
          <p>Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.</p>
          
          <p>The Company will take all steps reasonably necessary to ensure that Your data is treated securely and in accordance with this Privacy Policy and no transfer of Your Personal Data will take place to an organization or a country unless there are adequate controls in place including the security of Your data and other personal information.</p>
          
          <h3 className="text-2xl font-semibold mt-8 mb-3">Delete Your Personal Data</h3>
          <p>You have the right to delete or request that We assist in deleting the Personal Data that We have collected about You.</p>
          
          <p>Our Service may give You the ability to delete certain information about You from within the Service.</p>
          
          <p>You may update, amend, or delete Your information at any time by signing in to Your Account, if you have one, and visiting the account settings section that allows you to manage Your personal information. You may also contact Us to request access to, correct, or delete any personal information that You have provided to Us.</p>
          
          <p>Please note, however, that We may need to retain certain information when we have a legal obligation or lawful basis to do so.</p>
          
          <h3 className="text-2xl font-semibold mt-8 mb-3">Disclosure of Your Personal Data</h3>
          
          <h4 className="text-xl font-semibold mt-6 mb-2">Business Transactions</h4>
          <p>If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.</p>
          
          <h4 className="text-xl font-semibold mt-6 mb-2">Law enforcement</h4>
          <p>Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
          
          <h4 className="text-xl font-semibold mt-6 mb-2">Other legal requirements</h4>
          <p>The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:</p>
          
          <ul className="list-disc pl-6 space-y-2">
            <li>Comply with a legal obligation</li>
            <li>Protect and defend the rights or property of the Company</li>
            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
            <li>Protect the personal safety of Users of the Service or the public</li>
            <li>Protect against legal liability</li>
          </ul>
          
          <h3 className="text-2xl font-semibold mt-8 mb-3">Security of Your Personal Data</h3>
          <p>The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially reasonable means to protect Your Personal Data, We cannot guarantee its absolute security.</p>
          
          <h2 className="text-3xl font-bold mt-12 mb-4">Children's Privacy</h2>
          <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable information from anyone under the age of 13. If You are a parent or guardian and You are aware that Your child has provided Us with Personal Data, please contact Us. If We become aware that We have collected Personal Data from anyone under the age of 13 without verification of parental consent, We take steps to remove that information from Our servers.</p>
          
          <p>If We need to rely on consent as a legal basis for processing Your information and Your country requires consent from a parent, We may require Your parent's consent before We collect and use that information.</p>
          
          <h2 className="text-3xl font-bold mt-12 mb-4">Links to Other Websites</h2>
          <p>Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.</p>
          
          <p>We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>
          
          <h2 className="text-3xl font-bold mt-12 mb-4">Changes to this Privacy Policy</h2>
          <p>We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.</p>
          
          <p>We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.</p>
          
          <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.</p>
          
          <h2 className="text-3xl font-bold mt-12 mb-4">Contact Us</h2>
          <p>If you have any questions about this Privacy Policy, You can contact us:</p>
          
          <ul className="list-disc pl-6">
            <li>By visiting this page on our website: <a href="http://smart-asstor.com" rel="external nofollow noopener" target="_blank" className="text-primary hover:underline">http://smart-asstor.com</a></li>
          </ul>
        </article>
      </main>
      <Footer />
    </div>
  );
};

export default PrivacyPolicy;
